name: Publish feeds

on:
  schedule:
    - cron: "42 7,12,19 * * *"

jobs:
  publish_feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruicosta042/rssconv-action@main
